### ISSUE TITLE
No longer working in Cura 4.11.0

### ISSUE THREAD

**Issue by Filmman586** [Razor10021990/CuraSnapmakerSender#7]
I am no longer seeing the option in the drop down menu. Does this work with the new Cura?

**Comment by Razor10021990** [comment]
I haven't tried it.

But I will and give you feedback.

Louis Matarazzo ***@***.***> schrieb am Mo., 13. Sept. 2021,
23:55:

**Comment by Razor10021990** [comment]
So I don't have any problems. Even updated my firmware of the Printer, to check if it is a problem of the firmware. Please check the windows firewall settings. Seems like a problem on your side.
