### ISSUE TITLE
snapmaker sender issue

### ISSUE THREAD

**Issue by TechneCollab** [Razor10021990/CuraSnapmakerSender#8]
hey razor i am not sure if it is something in my setting but i am unable to connect cura to my snapmaker through the sender plugin. any remedy to this? can my fire wall block the app?

**Comment by Razor10021990** [comment]
So if Luban can find your printer, my plugin should also find it. But yes
if you block cura or parts of it in your firewall, then it can't work. You
can try to manually set the IP address of your snapmaker in the Settings of
my plugin. It can be, that the auto-discovery does not work in your network.

TechneCollab ***@***.***> schrieb am Do., 30. Sept. 2021,
08:15:
